"""init schema 18 tables

Revision ID: 34a67997e906
Revises: 
Create Date: 2026-09-27 12:34:51.873070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '34a67997e906'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anchor',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('owner_type', sa.String(length=32), nullable=False, comment='risk_item / contract_metadata'),
    sa.Column('owner_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False, comment='多态外键'),
    sa.Column('seq', sa.Integer(), nullable=False, comment='同一 owner 内多片段顺序'),
    sa.Column('page_no', sa.Integer(), nullable=False, comment='页码，从 1 开始'),
    sa.Column('bbox_x0', sa.Double(), nullable=False, comment='左上 X（PDF point）'),
    sa.Column('bbox_y0', sa.Double(), nullable=False),
    sa.Column('bbox_x1', sa.Double(), nullable=False, comment='右下 X'),
    sa.Column('bbox_y1', sa.Double(), nullable=False),
    sa.Column('char_start', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=True, comment='全文字符起始；扫描件为 NULL'),
    sa.Column('char_end', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=True, comment='字符结束（不含）'),
    sa.Column('quote_text', sa.String(length=512), nullable=True, comment='命中的原文片段，用于校验'),
    sa.Column('source', sa.String(length=16), nullable=False, comment='坐标来源'),
    sa.Column('anchor_level', sa.String(length=16), nullable=False, comment='对齐层级（exact/fuzzy/paragraph）'),
    sa.Column('confidence', sa.Double(), nullable=True, comment='OCR 置信度'),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anchor'))
    )
    op.create_index('idx_owner', 'anchor', ['owner_type', 'owner_id', 'seq'], unique=False)
    op.create_index('idx_page', 'anchor', ['page_no'], unique=False)
    op.create_table('contract',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='合同名称'),
    sa.Column('contract_no', sa.String(length=64), nullable=True, comment='合同编号'),
    sa.Column('business_type', sa.String(length=32), nullable=False, comment='业务类型，决定规则模板'),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='合同金额，未提取到为 NULL'),
    sa.Column('currency', sa.String(length=8), server_default=sa.text("'CNY'"), nullable=True, comment='币种'),
    sa.Column('applicant', sa.String(length=64), nullable=True, comment='申请人'),
    sa.Column('applicant_dept', sa.String(length=128), nullable=True, comment='送审部门'),
    sa.Column('counterparty_name', sa.String(length=255), nullable=True, comment='相对方主体名称'),
    sa.Column('counterparty_code', sa.String(length=32), nullable=True, comment='相对方统一社会信用代码'),
    sa.Column('file_format', sa.String(length=16), nullable=False, comment='文件格式，决定解析路径'),
    sa.Column('file_object_key', sa.String(length=512), nullable=False, comment='MinIO 原件 key'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_size', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False, comment='字节数'),
    sa.Column('file_hash', sa.CHAR(length=64), nullable=False, comment='SHA-256，去重用'),
    sa.Column('pdf_object_key', sa.String(length=512), nullable=True, comment='转换后 PDF 的 key'),
    sa.Column('source', sa.String(length=16), server_default=sa.text("'upload'"), nullable=False, comment='来源渠道'),
    sa.Column('external_id', sa.String(length=128), nullable=True, comment='审批系统单号'),
    sa.Column('deleted_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=True, comment='软删除标记，NULL = 活跃'),
    sa.Column('deleted_key', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), sa.Computed("IFNULL(deleted_at, '1970-01-01 00:00:00.000')", persisted=True), nullable=False, comment='生成列：NULL 归一化哨兵，仅供唯一键使用，不可写入'),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contract'))
    )
    op.create_index('idx_business_type', 'contract', ['business_type'], unique=False)
    op.create_index('idx_created_at', 'contract', ['created_at'], unique=False)
    op.create_index('idx_external_id', 'contract', ['external_id'], unique=False)
    op.create_index('uk_file_hash', 'contract', ['file_hash', 'deleted_key'], unique=True)
    op.create_table('rule_template',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('contract_type', sa.String(length=32), nullable=False, comment='适用的业务类型'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='模板名称'),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('enabled', sa.SmallInteger().with_variant(mysql.TINYINT(display_width=1), 'mysql'), server_default=sa.text('1'), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_template'))
    )
    op.create_index('uk_contract_type', 'rule_template', ['contract_type'], unique=True)
    op.create_table('standard_clause',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('clause_type', sa.String(length=32), nullable=False, comment='条款类型'),
    sa.Column('contract_type', sa.String(length=32), nullable=True, comment='适用业务类型；NULL 表示通用'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='条款标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='标准条款正文'),
    sa.Column('source', sa.String(length=255), nullable=True, comment='来源说明（法条 / 行业惯例）'),
    sa.Column('enabled', sa.SmallInteger().with_variant(mysql.TINYINT(display_width=1), 'mysql'), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_standard_clause'))
    )
    op.create_index('idx_type_business', 'standard_clause', ['clause_type', 'contract_type'], unique=False)
    op.create_table('subject_blacklist',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('subject_name', sa.String(length=255), nullable=False, comment='主体名称'),
    sa.Column('credit_code', sa.String(length=32), nullable=True, comment='统一社会信用代码'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='经营异常 / 严重违法失信 / 注销'),
    sa.Column('detail', sa.String(length=512), nullable=True, comment='详情'),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject_blacklist'))
    )
    op.create_index('idx_credit_code', 'subject_blacklist', ['credit_code'], unique=False)
    op.create_index('idx_subject_name', 'subject_blacklist', ['subject_name'], unique=False)
    op.create_table('export_record',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False, comment='markdown / pdf'),
    sa.Column('file_object_key', sa.String(length=512), nullable=False, comment='MinIO object key'),
    sa.Column('file_size', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=True, comment='字节数'),
    sa.Column('created_by', sa.String(length=64), nullable=True, comment='导出人'),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], name=op.f('fk_export_record_contract_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_export_record'))
    )
    op.create_index('idx_contract_created', 'export_record', ['contract_id', 'created_at'], unique=False)
    op.create_table('review_task',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False, comment='FK → contract.id'),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False, comment='任务状态'),
    sa.Column('writeback_status', sa.String(length=16), server_default=sa.text("'not_written'"), nullable=False, comment='回写状态'),
    sa.Column('blocked_reason', sa.String(length=32), nullable=True, comment='仅 blocked 时非空'),
    sa.Column('blocked_detail', sa.String(length=512), nullable=True, comment='阻塞详情'),
    sa.Column('overall_risk', sa.String(length=8), nullable=True, comment='整体风险等级'),
    sa.Column('conclusion', sa.String(length=16), nullable=True, comment='审查结论'),
    sa.Column('summary', sa.Text(), nullable=True, comment='综合风险摘要'),
    sa.Column('total_pages', sa.Integer(), nullable=True, comment='解析后确定的总页数'),
    sa.Column('parsed_pages', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='已解析页数'),
    sa.Column('high_risk_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('medium_risk_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('low_risk_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('parse_duration_ms', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=True),
    sa.Column('review_duration_ms', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=True),
    sa.Column('started_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=True, comment='进入 parsing 的时刻'),
    sa.Column('blocked_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=True, comment='进入 blocked 的时刻'),
    sa.Column('completed_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=True, comment='进入 completed 的时刻'),
    sa.Column('version', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), server_default=sa.text('0'), nullable=False, comment='乐观锁'),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], name=op.f('fk_review_task_contract_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_task'))
    )
    op.create_index('idx_overall_risk', 'review_task', ['overall_risk'], unique=False)
    op.create_index('idx_status', 'review_task', ['status'], unique=False)
    op.create_index('idx_status_created', 'review_task', ['status', 'created_at'], unique=False)
    op.create_index('uk_contract_id', 'review_task', ['contract_id'], unique=True)
    op.create_table('rule',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False, comment='规则编码，如 LIABILITY_UNEQUAL'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='规则名称'),
    sa.Column('category', sa.String(length=32), nullable=False, comment='风险分类'),
    sa.Column('risk_level', sa.String(length=8), nullable=False, comment='命中后的风险等级'),
    sa.Column('rule_type', sa.String(length=16), nullable=False, comment='匹配方式'),
    sa.Column('config', mysql.JSON().with_variant(sa.Text(), 'sqlite'), nullable=True, comment='类型相关参数'),
    sa.Column('result_template', sa.Text(), nullable=True, comment='结论模板，支持 {占位符}'),
    sa.Column('suggestion_template', sa.Text(), nullable=True, comment='推荐修改条款模板'),
    sa.Column('enabled', sa.SmallInteger().with_variant(mysql.TINYINT(display_width=1), 'mysql'), server_default=sa.text('1'), nullable=False),
    sa.Column('seq', sa.Integer(), server_default='0', nullable=False, comment='执行顺序'),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['rule_template.id'], name=op.f('fk_rule_template_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule'))
    )
    op.create_index('idx_enabled', 'rule', ['enabled'], unique=False)
    op.create_index('uk_template_code', 'rule', ['template_id', 'code'], unique=True)
    op.create_table('writeback_log',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False, comment='回写状态'),
    sa.Column('payload', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=False, comment='发送的 Markdown 文本'),
    sa.Column('response', sa.Text(), nullable=True, comment='审批系统返回原文'),
    sa.Column('http_status', sa.Integer(), nullable=True, comment='HTTP 状态码'),
    sa.Column('retry_count', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), server_default='0', nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True, comment='失败详情'),
    sa.Column('duration_ms', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], name=op.f('fk_writeback_log_contract_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_writeback_log'))
    )
    op.create_index('idx_contract_created', 'writeback_log', ['contract_id', 'created_at'], unique=False)
    op.create_index('idx_status', 'writeback_log', ['status'], unique=False)
    op.create_table('llm_call_log',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False, comment='mock / openai_compat'),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('purpose', sa.String(length=32), nullable=False, comment='clause_review / suggestion / summary'),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('json_retry_count', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), server_default='0', nullable=False, comment='JSON 解析重试次数'),
    sa.Column('duration_ms', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['review_task.id'], name=op.f('fk_llm_call_log_task_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_call_log'))
    )
    op.create_index('idx_status', 'llm_call_log', ['status'], unique=False)
    op.create_index('idx_task_id', 'llm_call_log', ['task_id'], unique=False)
    op.create_table('parse_result',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('task_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('parse_method', sa.String(length=32), nullable=False, comment='实际生效的解析路径'),
    sa.Column('converter_used', sa.String(length=32), nullable=True, comment='生效的 DOCX 转换器'),
    sa.Column('converter_fallback_chain', sa.String(length=255), nullable=True, comment='降级链，如 wps_com>libreoffice>passthrough'),
    sa.Column('ocr_engine', sa.String(length=32), nullable=True, comment='OCR 引擎名'),
    sa.Column('ocr_dpi', sa.Integer(), nullable=True, comment='渲染 DPI'),
    sa.Column('page_count', sa.Integer(), nullable=False, comment='总页数'),
    sa.Column('failed_pages', sa.String(length=512), nullable=True, comment='失败页号，逗号分隔'),
    sa.Column('has_text_layer', sa.SmallInteger().with_variant(mysql.TINYINT(display_width=1), 'mysql'), server_default=sa.text('0'), nullable=False, comment='是否有原生文本层'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='解析成败状态'),
    sa.Column('avg_confidence', sa.Double(), nullable=True, comment='OCR 平均置信度'),
    sa.Column('duration_ms', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('attempt', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), server_default=sa.text('1'), nullable=False, comment='第几次尝试'),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], name=op.f('fk_parse_result_contract_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['review_task.id'], name=op.f('fk_parse_result_task_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parse_result'))
    )
    op.create_index('idx_contract_attempt', 'parse_result', ['contract_id', 'attempt'], unique=False)
    op.create_index('idx_task_id', 'parse_result', ['task_id'], unique=False)
    op.create_table('rule_condition',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('seq', sa.Integer(), server_default='0', nullable=False, comment='条件顺序'),
    sa.Column('field', sa.String(length=64), nullable=False, comment='作用字段，如 clause.content / metadata.amount'),
    sa.Column('operator', sa.String(length=16), nullable=False, comment='比较运算符'),
    sa.Column('value', sa.Text(), nullable=True, comment='比较值；exists/not_exists 时为空'),
    sa.Column('value_type', sa.String(length=16), server_default=sa.text("'string'"), nullable=False, comment='值类型标签'),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], name=op.f('fk_rule_condition_rule_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_condition'))
    )
    op.create_index('idx_rule_seq', 'rule_condition', ['rule_id', 'seq'], unique=False)
    op.create_table('task_event',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False, comment='事件类型'),
    sa.Column('from_status', sa.String(length=16), nullable=True, comment='变更前状态'),
    sa.Column('to_status', sa.String(length=16), nullable=True, comment='变更后状态'),
    sa.Column('operator', sa.String(length=64), nullable=True, comment='操作人；系统操作为 system'),
    sa.Column('detail', sa.String(length=1024), nullable=True, comment='事件详情'),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['review_task.id'], name=op.f('fk_task_event_task_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_event'))
    )
    op.create_index('idx_task_created', 'task_event', ['task_id', 'created_at'], unique=False)
    op.create_table('clause',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('parse_result_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False, comment='标明产物来源'),
    sa.Column('clause_type', sa.String(length=32), nullable=False, comment='条款类型'),
    sa.Column('clause_no', sa.String(length=32), nullable=True, comment='条款序号，如 第三条 / 3.2'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='条款标题'),
    sa.Column('content', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=False, comment='条款正文'),
    sa.Column('page_no', sa.Integer(), nullable=False, comment='起始页码，从 1 开始'),
    sa.Column('page_end', sa.Integer(), nullable=True, comment='结束页码（跨页条款）'),
    sa.Column('para_index', sa.Integer(), nullable=False, comment='段落索引，从 0 开始'),
    sa.Column('char_start', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=True, comment='全文中的字符起始；扫描件为 NULL'),
    sa.Column('char_end', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=True, comment='字符结束（不含）'),
    sa.Column('bbox_x0', sa.Double(), nullable=True, comment='起始页坐标（PDF point）'),
    sa.Column('bbox_y0', sa.Double(), nullable=True),
    sa.Column('bbox_x1', sa.Double(), nullable=True),
    sa.Column('bbox_y1', sa.Double(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False, comment='在文档中的顺序'),
    sa.Column('source', sa.String(length=16), nullable=False, comment='坐标来源'),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], name=op.f('fk_clause_contract_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parse_result_id'], ['parse_result.id'], name=op.f('fk_clause_parse_result_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clause'))
    )
    op.create_index('idx_contract_seq', 'clause', ['contract_id', 'seq'], unique=False)
    op.create_index('idx_contract_type', 'clause', ['contract_id', 'clause_type'], unique=False)
    op.create_index('idx_parse_result', 'clause', ['parse_result_id'], unique=False)
    op.create_table('contract_metadata',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('parse_result_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('meta_key', sa.String(length=64), nullable=False, comment='元数据键'),
    sa.Column('meta_value', sa.String(length=1024), nullable=True, comment='原始值（字符串形式）'),
    sa.Column('value_normalized', sa.String(length=512), nullable=True, comment='归一化值（金额→数字串、日期→ISO）'),
    sa.Column('value_type', sa.String(length=16), nullable=False, comment='string / decimal / date'),
    sa.Column('confidence', sa.Double(), server_default=sa.text('1.0'), nullable=False, comment='提取置信度'),
    sa.Column('need_review', sa.SmallInteger().with_variant(mysql.TINYINT(display_width=1), 'mysql'), server_default=sa.text('0'), nullable=False, comment='OCR 低置信时置 1，UI 高亮待核对'),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], name=op.f('fk_contract_metadata_contract_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parse_result_id'], ['parse_result.id'], name=op.f('fk_contract_metadata_parse_result_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contract_metadata'))
    )
    op.create_index('idx_need_review', 'contract_metadata', ['contract_id', 'need_review'], unique=False)
    op.create_index('uk_contract_key', 'contract_metadata', ['contract_id', 'meta_key'], unique=True)
    op.create_table('risk_item',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('clause_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=True, comment='全局性问题为 NULL'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='风险项名称'),
    sa.Column('risk_level', sa.String(length=8), nullable=False, comment='风险等级'),
    sa.Column('category', sa.String(length=32), nullable=False, comment='风险分类'),
    sa.Column('reason', sa.Text(), nullable=False, comment='风险成因（面向用户）'),
    sa.Column('legal_basis', sa.Text(), nullable=True, comment='法律合规依据'),
    sa.Column('suggestion', sa.Text(), nullable=True, comment='AI 推荐修改条款'),
    sa.Column('suggestion_edited', sa.Text(), nullable=True, comment='法务编辑版，非空时优先展示'),
    sa.Column('adopted', sa.SmallInteger().with_variant(mysql.TINYINT(display_width=1), 'mysql'), server_default=sa.text('0'), nullable=False, comment='法务是否采纳建议'),
    sa.Column('merged_by', sa.String(length=8), nullable=False, comment='定级来源，实现双来源留痕'),
    sa.Column('is_global', sa.SmallInteger().with_variant(mysql.TINYINT(display_width=1), 'mysql'), server_default=sa.text('0'), nullable=False, comment='是否全局性问题（非条款级）'),
    sa.Column('unanchored', sa.SmallInteger().with_variant(mysql.TINYINT(display_width=1), 'mysql'), server_default=sa.text('0'), nullable=False, comment='引用无法定位（防幻觉闸门标记）'),
    sa.Column('seq', sa.Integer(), nullable=False, comment='展示顺序（按等级+页码固化）'),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clause.id'], name=op.f('fk_risk_item_clause_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], name=op.f('fk_risk_item_contract_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_item'))
    )
    op.create_index('idx_clause_id', 'risk_item', ['clause_id'], unique=False)
    op.create_index('idx_contract_level', 'risk_item', ['contract_id', 'risk_level'], unique=False)
    op.create_index('idx_contract_seq', 'risk_item', ['contract_id', 'seq'], unique=False)
    op.create_index('idx_unanchored', 'risk_item', ['unanchored'], unique=False)
    op.create_table('annotation',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('risk_item_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=True, comment='整体意见为 NULL'),
    sa.Column('author', sa.String(length=64), nullable=False, comment='批注人'),
    sa.Column('author_role', sa.String(length=32), nullable=True, comment='角色，如 法务审查人'),
    sa.Column('content', sa.Text(), nullable=False, comment='批注内容'),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], name=op.f('fk_annotation_contract_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_item_id'], ['risk_item.id'], name=op.f('fk_annotation_risk_item_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_annotation'))
    )
    op.create_index('idx_contract_created', 'annotation', ['contract_id', 'created_at'], unique=False)
    op.create_index('idx_risk_item', 'annotation', ['risk_item_id'], unique=False)
    op.create_table('risk_evidence',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('risk_item_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('evidence_type', sa.String(length=16), nullable=False, comment='依据来源'),
    sa.Column('rule_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=True, comment='evidence_type=rule 时的来源规则'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='依据标题，如《民法典》第五百八十五条'),
    sa.Column('detail', sa.Text(), nullable=False, comment='依据详情'),
    sa.Column('raw_snippet', sa.Text(), nullable=True, comment='LLM 原始输出片段（审计用）'),
    sa.Column('need_review', sa.SmallInteger().with_variant(mysql.TINYINT(display_width=1), 'mysql'), server_default=sa.text('0'), nullable=False, comment='LLM 编造法条时置 1'),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['risk_item_id'], ['risk_item.id'], name=op.f('fk_risk_evidence_risk_item_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], name=op.f('fk_risk_evidence_rule_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_evidence'))
    )
    op.create_index('idx_risk_item', 'risk_evidence', ['risk_item_id', 'evidence_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚：删除全部 18 张表。

    注意：**只删表，不显式 drop_index**。

    autogenerate 默认会为每个索引生成 `op.drop_index`，但在 MySQL 下，
    支撑外键的索引不允许被单独删除（报错 1553 "Cannot drop index ...:
    needed in a foreign key constraint"）。而 `DROP TABLE` 本身就会连带
    删除该表的索引与外键，因此显式 drop_index 既冗余又有害，已实测。

    删除顺序为建表顺序的逆序（子表先于父表），满足外键约束。
    """
    op.drop_table("risk_evidence")
    op.drop_table("annotation")
    op.drop_table("risk_item")
    op.drop_table("clause")
    op.drop_table("contract_metadata")
    op.drop_table("parse_result")
    op.drop_table("task_event")
    op.drop_table("llm_call_log")
    op.drop_table("rule_condition")
    op.drop_table("rule")
    op.drop_table("writeback_log")
    op.drop_table("export_record")
    op.drop_table("review_task")
    op.drop_table("contract")
    op.drop_table("anchor")
    op.drop_table("standard_clause")
    op.drop_table("subject_blacklist")
    op.drop_table("rule_template")
